### ISSUE TITLE
Init.sql file

### ISSUE THREAD

**Issue by ZaziroZ** [kemalyuksel/Sale-Stock-Invoice-System#1]
Great job creating this!

Isn't an init.sql file missing?

**Comment by kemalyuksel** [comment]
![issue](https://user-images.githubusercontent.com/44436109/116714152-1ed45d80-a9de-11eb-8a3f-b0a99c55cb9a.png)

If you want to use it on your own computer, you need to change the settings like ;

firstly you need to create schema  , name like 'projectdb' on Mysql

Row 1  = 'create' ( to create the tables for first time  ) and change 'update' 
Row 3 = your mysql username
Row 4 = your mysql password

**Comment by ZaziroZ** [comment]
Thanks a lot!

**Comment by ZaziroZ** [comment]
I've just got back to it.

Okay, this solution will generate the tables. But what about data? Such as user roles, concrete users etc?

**Comment by kemalyuksel** [comment]
You need to use spring security for user roles and user authorization and authantication
